import { StrictMode } from "react"
import { createRoot } from "react-dom/client"
import { App } from "./app/App"
import { LanguageProvider } from "./i18n/i18n"
import { initializeTheme } from "./theme/theme"
import "./styles/tokens.css"
import "./styles/global.css"
import "./styles/constellation.css"
import "./styles/org-walk.css"
import "./styles/polish.css"
import "./styles/saved-map.css"
import "./styles/career-leads.css"
import "./styles/methodology.css"
import "./styles/constellation-signals.css"
import "./styles/roles.css"
import "./styles/org-walk-virtual.css"
import "./styles/filters.css"
import "./styles/discover.css"
import "./styles/people.css"
import "./styles/theme-overrides.css"
import "./styles/border-glow.css"
import "./styles/premium.css"
import "./styles/button-glow.css"
import "./styles/magic-bubbles.css"
initializeTheme()
createRoot(document.getElementById("root")!).render(<StrictMode><LanguageProvider><App /></LanguageProvider></StrictMode>)
