import { StrictMode } from "react"
import { createRoot } from "react-dom/client"
import { App } from "./app/App"
import "./styles/tokens.css"
import "./styles/global.css"
import "./styles/constellation.css"
import "./styles/org-walk.css"
import "./styles/polish.css"
import "./styles/saved-map.css"
createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>)
