import { StrictMode } from "react"
import { createRoot } from "react-dom/client"
import { App } from "./app/App"
import { LanguageProvider } from "./i18n/i18n"
import "./styles/tokens.css"
import "./styles/global.css"
import "./styles/constellation.css"
import "./styles/org-walk.css"
import "./styles/polish.css"
import "./styles/saved-map.css"
import "./styles/career-leads.css"
import "./styles/methodology.css"
createRoot(document.getElementById("root")!).render(<StrictMode><LanguageProvider><App /></LanguageProvider></StrictMode>)
