from __future__ import annotations

from typing import Any, Protocol


class CareerReadStore(Protocol):
    """Provider-neutral read-only seam for the public Career Atlas API."""

    def meta(self) -> dict[str, object]: ...
    def search(self, *, query: str, limit: int = 20) -> Any: ...
    def departments(self) -> Any: ...
    def children(self, *, parent_id: str | None, limit: int = 50) -> Any: ...
    def ancestors(self, org_id: str) -> Any: ...
    def team_profile(self, org_id: str) -> Any: ...
    def people(self, *, org_id: str, query: str = "", classification: str | None = None, sort: str = "name", limit: int = 50, offset: int = 0) -> Any: ...
    def roles(self, *, org_id: str | None = None, limit: int = 50) -> Any: ...
    def vacancy_signals(self, *, limit: int = 50) -> Any: ...
    def constellation(self, *, query: str, limit: int = 200) -> Any: ...
    def constellation_slice(self, *, root_id: str | None, max_depth: int = 1, limit: int = 200, category: str | None = None) -> Any: ...
    def tours(self) -> Any: ...
